# Generated by Django 5.2.8 on 2025-11-28 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Instruments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instrument',
            options={'ordering': ['-time_created']},
        ),
        migrations.AddField(
            model_name='instrument',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=100),
        ),
        migrations.AddIndex(
            model_name='instrument',
            index=models.Index(fields=['-time_created'], name='Instruments_time_cr_f0ee3b_idx'),
        ),
    ]
