# Generated by Django 5.2.8 on 2025-11-28 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Instruments', '0002_alter_instrument_options_instrument_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrument',
            name='slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]
