# Generated by Django 5.2.8 on 2025-11-28 10:13

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Instruments', '0003_alter_instrument_slug'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='instrument',
            managers=[
                ('published_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='instrument',
            name='is_published',
            field=models.BooleanField(choices=[(0, 'Не актуально'), (1, 'Опубликовано')], default=1),
        ),
    ]
