# Generated by Django 5.2.8 on 2025-11-28 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Instruments', '0005_instrumentcategory_instrument_cat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrument',
            name='cat',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='Instruments.instrumentcategory'),
            preserve_default=False,
        ),
    ]
