# Generated by Django 5.2.8 on 2025-11-28 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Instruments', '0006_alter_instrument_cat'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagInstrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(db_index=True, max_length=100)),
                ('slug', models.SlugField(max_length=255, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='instrument',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instruments', to='Instruments.instrumentcategory'),
        ),
        migrations.AddField(
            model_name='instrument',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='instruments', to='Instruments.taginstrument'),
        ),
    ]
