# Generated by Django 5.2.8 on 2025-12-01 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Instruments', '0007_taginstrument_alter_instrument_cat_instrument_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taginstrument',
            old_name='tag',
            new_name='name',
        ),
    ]
