# Generated by Django 5.2.8 on 2025-12-01 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Instruments', '0008_rename_tag_taginstrument_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstrumentSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accuracy', models.IntegerField(blank=True, null=True, verbose_name='Точность')),
                ('resolution', models.IntegerField(blank=True, null=True, verbose_name='Разрешение')),
                ('method', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='instrument',
            name='specifications',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instrument', to='Instruments.instrumentspecification'),
        ),
    ]
