# Generated by Django 5.2.8 on 2025-12-01 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Instruments', '0009_instrumentspecification_instrument_specifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrumentspecification',
            name='accuracy',
            field=models.CharField(blank=True, null=True, verbose_name='Точность'),
        ),
        migrations.AlterField(
            model_name='instrumentspecification',
            name='resolution',
            field=models.CharField(blank=True, null=True, verbose_name='Разрешение'),
        ),
    ]
