# Generated by Django 5.2.8 on 2025-12-01 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Instruments', '0010_alter_instrumentspecification_accuracy_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instrument',
            options={'ordering': ['-time_created'], 'verbose_name': 'лабораторное оборудование', 'verbose_name_plural': 'лабораторное оборудование'},
        ),
        migrations.AlterModelOptions(
            name='instrumentcategory',
            options={'verbose_name': 'Категории оборудования', 'verbose_name_plural': 'Категории оборудования'},
        ),
        migrations.AlterModelOptions(
            name='taginstrument',
            options={'verbose_name': 'Тэги для оборудования', 'verbose_name_plural': 'Тэги для оборудования'},
        ),
        migrations.AlterField(
            model_name='instrument',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instruments', to='Instruments.instrumentcategory', verbose_name='категории'),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='content',
            field=models.TextField(blank=True, verbose_name='содержание'),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='is_published',
            field=models.IntegerField(choices=[(0, 'снято с производства'), (1, 'доступно')], default=1, verbose_name='актуальность'),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='specifications',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instrument', to='Instruments.instrumentspecification', verbose_name='спецификация'),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='instruments', to='Instruments.taginstrument', verbose_name='тэги'),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='title',
            field=models.CharField(max_length=100, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='instrumentcategory',
            name='name',
            field=models.CharField(max_length=100, verbose_name='название категории'),
        ),
        migrations.AlterField(
            model_name='taginstrument',
            name='name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='название тэга'),
        ),
        migrations.AlterField(
            model_name='taginstrument',
            name='slug',
            field=models.SlugField(max_length=255, unique=True, verbose_name='слаг'),
        ),
    ]
