# Generated by Django 5.2.8 on 2025-12-03 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Instruments', '0011_alter_instrument_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads_instrument')),
            ],
        ),
        migrations.AlterModelManagers(
            name='instrument',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='instrument',
            name='is_published',
            field=models.IntegerField(choices=[(0, 'снято с производства'), (1, 'доступно')], default=0, verbose_name='актуальность'),
        ),
    ]
