# Generated by Django 5.2.8 on 2025-12-03 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Instruments', '0012_uploadedfiles_alter_instrument_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrument',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='images/<django.db.models.fields.SlugField>', verbose_name='image'),
        ),
    ]
