# Generated by Django 5.2.8 on 2025-12-04 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Instruments', '0013_instrument_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrument',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='images/', verbose_name='image'),
        ),
    ]
